package com.deerflow.mobile.ui

enum class AppRoute(val path: String) {
    Workspace("workspace"),
    Conversation("conversation"),
    Agents("agents"),
    Tasks("tasks"),
    Memory("memory"),
    Profile("profile"),
}

internal val AppRoute.isWorkspaceChild: Boolean
    get() = this in setOf(AppRoute.Agents, AppRoute.Tasks, AppRoute.Memory, AppRoute.Profile)

/** Workspace and conversation share ChatScreen, so switching between them must not animate a page swap. */
internal fun AppRoute.workspacePageRoute(): AppRoute =
    if (isWorkspaceChild) this else AppRoute.Workspace

enum class DrawerDestination {
    NewConversation,
    Agents,
    Tasks,
    Skills,
    Memory,
}

object UiTags {
    const val LoginScreen = "login-screen"
    const val SsoProviderPrefix = "sso-provider-"
    const val SsoWebView = "sso-web-view"
    const val WorkspaceDrawer = "workspace-drawer"
    const val NewChatButton = "new-chat-button"
    const val ConversationSearch = "conversation-search"
    const val ChatTopBar = "chat-top-bar"
    const val ChatNavigationButton = "chat-navigation-button"
    const val ConversationExportButton = "conversation-export-button"
    const val ThreadRowPrefix = "thread-row-"
    const val ThreadPinAction = "thread-pin-action"
    const val ThreadRenameAction = "thread-rename-action"
    const val ThreadDeleteAction = "thread-delete-action"
    const val ThreadRenameTitle = "thread-rename-title"
    const val ThreadRenameSave = "thread-rename-save"
    const val ThreadDeleteConfirm = "thread-delete-confirm"
    const val ChatScreen = "chat-screen"
    const val HumanInputText = "human-input-text"
    const val HumanInputSubmit = "human-input-submit"
    const val Composer = "message-composer"
    const val ComposerInput = "message-composer-input"
    const val ComposerAttachmentButton = "composer-attachment-button"
    const val SendStopButton = "send-stop-button"
    const val AttachmentSheet = "attachment-sheet"
    const val TopSelectors = "top-selectors"
    const val ModelSelector = "model-selector"
    const val ModeSelector = "mode-selector"
    const val ProcessingCard = "processing-card"
    const val QuickCapabilities = "quick-capabilities"
    const val SkillsSheet = "skills-sheet"
    const val SkillsGrid = "skills-grid"
    const val SkillsSearch = "skills-search"
    const val SkillCardPrefix = "skill-card-"
    const val SkillGlobalEnablePrefix = "skill-global-enable-"
    const val SkillDetailScreen = "skill-detail-screen"
    const val SkillDetailBack = "skill-detail-back"
    const val SkillDetailSelect = "skill-detail-select"
    const val SkillDetailGlobalEnable = "skill-detail-global-enable"
    const val McpSheet = "mcp-sheet"
    const val McpServerPrefix = "mcp-server-"
    const val McpServerEnablePrefix = "mcp-server-enable-"
    const val McpConfigEdit = "mcp-config-edit"
    const val McpConfigEditor = "mcp-config-editor"
    const val McpConfigRawJson = "mcp-config-raw-json"
    const val McpConfigSave = "mcp-config-save"
    const val ChannelsSheet = "channels-sheet"
    const val ChannelProviderPrefix = "channel-provider-"
    const val ChannelConnectPrefix = "channel-connect-"
    const val ChannelConfigurePrefix = "channel-configure-"
    const val ChannelDisablePrefix = "channel-disable-"
    const val ChannelCredentialPrefix = "channel-credential-"
    const val ChannelConfigSave = "channel-config-save"
    const val ChannelBindingCode = "channel-binding-code"
    const val AgentRowPrefix = "agent-row-"
    const val AgentDefaultPrefix = "agent-default-"
    const val AgentDetailScreen = "agent-detail-screen"
    const val AgentDetailEdit = "agent-detail-edit"
    const val AgentDetailChat = "agent-detail-chat"
    const val AgentDetailHistory = "agent-detail-history"
    const val AgentDetailDefault = "agent-detail-default"
    const val AgentDetailSetDefault = "agent-detail-set-default"
    const val AgentEditorName = "agent-editor-name"
    const val AgentEditorDescription = "agent-editor-description"
    const val AgentEditorModelPrefix = "agent-editor-model-"
    const val AgentEditorSave = "agent-editor-save"
    const val AgentEditorDelete = "agent-editor-delete"
    const val AgentRunHistorySheet = "agent-run-history-sheet"
    const val AgentRunPrefix = "agent-run-"
    const val AgentRunDetail = "agent-run-detail"
    const val AgentRunOpenConversation = "agent-run-open-conversation"
    const val TaskRowPrefix = "task-row-"
    const val TaskRunNow = "task-run-now"
    const val TaskHistoryPrefix = "task-history-"
    const val TaskMoreActions = "task-more-actions"
    const val TaskPauseResume = "task-pause-resume"
    const val TaskEdit = "task-edit"
    const val TaskDelete = "task-delete"
    const val TaskEditorTitle = "task-editor-title"
    const val TaskEditorPrompt = "task-editor-prompt"
    const val TaskEditorScheduleCron = "task-editor-schedule-cron"
    const val TaskEditorScheduleOnce = "task-editor-schedule-once"
    const val TaskEditorCron = "task-editor-cron"
    const val TaskEditorOnceDate = "task-editor-once-date"
    const val TaskEditorOnceTime = "task-editor-once-time"
    const val TaskEditorTimezone = "task-editor-timezone"
    const val TaskEditorSave = "task-editor-save"
    const val TaskRunHistorySheet = "task-run-history-sheet"
    const val TaskRunPrefix = "task-run-"
    const val TaskRunOpenConversation = "task-run-open-conversation"
    const val MemoryScreen = "memory-screen"
    const val MemorySearch = "memory-search"
    const val MemoryAddFact = "memory-add-fact"
    const val MemoryMoreActions = "memory-more-actions"
    const val MemoryClearAction = "memory-clear-action"
    const val MemoryFilterPrefix = "memory-filter-"
    const val MemoryFactContent = "memory-fact-content"
    const val MemoryFactSave = "memory-fact-save"
    const val MemoryFactDetailEdit = "memory-fact-detail-edit"
    const val MemoryFactDetailDelete = "memory-fact-detail-delete"
    const val MemoryFactDeleteConfirm = "memory-fact-delete-confirm"
    const val MemoryClearConfirm = "memory-clear-confirm"
    const val MemoryFactPrefix = "memory-fact-"
    const val ProfileScreen = "profile-screen"
    const val ProfileList = "profile-list"
    const val ProfileChannels = "profile-channels"
    const val ProfileServer = "profile-server"
    const val ProfileThemePrefix = "profile-theme-"
    const val ProfileLanguage = "profile-language"
    const val ProfileLanguageOptionPrefix = "profile-language-option-"
    const val ProfileNotifications = "profile-notifications"
    const val ProfileCacheRefresh = "profile-cache-refresh"
    const val ProfileCachePolicy = "profile-cache-policy"
    const val ProfileCachePolicyOptionPrefix = "profile-cache-policy-option-"
    const val ProfileCacheClear = "profile-cache-clear"
    const val ProfileCacheClearConfirm = "profile-cache-clear-confirm"
    const val ProfileAbout = "profile-about"
    const val AboutScreen = "about-screen"
    const val AboutBack = "about-back"
    const val AboutDeerFlowLicense = "about-deerflow-license"
    const val AboutOpenSourceLicenses = "about-open-source-licenses"
    const val ThirdPartyLicensesScreen = "third-party-licenses-screen"
    const val AboutSourceCode = "about-source-code"
    const val AboutLicenseDialog = "about-license-dialog"
}
